# Generated by Django 4.2.22 on 2025-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
